export const defaultLang = 'en';

export const ui = {
    en: {
        "about": "About me",
        "experience": "Experience",
        "projects": "Projects",
        "uniProjects": "University Projects",
        "contact": "Contact Form",
        "hero.swipe": "Swipe down to see more",
        "project.source": "Source",
        "project.preview": "Preview",
        "project.post": "Post",
        "project.in_development": "In Development",
        "contact.foreword": "Thank you for stopping by. Whether you are recruiter with a potential opportunity, represent a team looking for a developer, have an interesting idea to build together, or simply want to connect, feel free to leave a note below. I am always glad to hear from others and will be sure to get in touch promptly.",
        "contact.name": "Your full name",
        "contact.email": "Your email",
        "contact.type": "Type of message",
        "contact.option": "-- select an option --",
        "contact.option.work": "Work & Collaboration",
        "contact.option.networking": "Networking & Professional Connections",
        "contact.option.feedback": "Feedback/suggestion for the website",
        "contact.option.job": "Job Offers & Recruiter Outreach",
        "contact.option.other": "Other",
        "contact.message": "Message",
        "contact.send": "Send",
        "contact.sending": "Sending...",
        "contact.success": 'Sent successfully',
        "contact.err_captcha": "Looks like you missed the reCAPTCHA box. Please complete it to submit your message.",
        "contact.err_select": "You did not fill the 'Type of Message' in the box. Please select it.'",
        "contact.err_general": "Error occurred! Try again later or email directly at contact@badamczyk.eu",
        "contact.disclaimer1": "The messages are sent via ",
        "contact.disclaimer2": " and are not stored on the server",
    },
    pl: {
        "about": "O mnie",
        "experience": "Doświadczenie",
        "projects": "Projekty",
        "uniProjects": "Projekty uczelniane",
        "contact": "Formularz kontaktowy",
        "hero.swipe": "Przewiń w dół, aby dowiedzieć się więcej",
        "project.source": "Źródło",
        "project.preview": "Podgląd",
        "project.post": "Post",
        "project.in_development": "W przygotowaniu",
        "contact.foreword": "Dziękuję za wizytę na mojej stronie. Niezależnie od tego, czy jesteś rekruterem z ciekawą ofertą, reprezentujesz zespół szukający programisty, masz interesujący pomysł na wspólny projekt, czy po prostu chcesz nawiązać kontakt — zostaw wiadomość poniżej. Zawsze chętnie odpowiadam na nowe wiadomości i skontaktuję się z Tobą najszybciej, jak to możliwe.",
        "contact.name": "Imię i nazwisko",
        "contact.email": "Twój e-mail",
        "contact.type": "Temat wiadomości",
        "contact.option": "-- wybierz opcję --",
        "contact.option.work": "Współpraca",
        "contact.option.networking": "Networking i kontakty zawodowe",
        "contact.option.feedback": "Opinie/sugestie dotyczące strony",
        "contact.option.job": "Oferty pracy i kontakt od rekrutera",
        "contact.option.other": "Inne",
        "contact.message": "Treść wiadomości",
        "contact.send": "Wyślij",
        "contact.sending": "Wysyłanie...",
        "contact.success": "Pomyślnie wysłano",
        "contact.err_captcha": "Wygląda na to, że pominąłeś pole reCAPTCHA. Zaznacz je, aby wysłać wiadomość.",
        "contact.err_select": "Nie wypełniłeś pola 'Temat wiadomości' w oknie. Proszę go wybrać.",
        "contact.err_general": "Wystąpił błąd! Spróbuj ponownie później lub napisz bezpośrednio na adres contact@badamczyk.eu",
        "contact.disclaimer1": "Wiadomości są wysyłane za pośrednictwem ",
        "contact.disclaimer2": " i nie są przechowywane na serwerze",
    },
    nl: {
        "about": "Over mij",
        "experience": "Ervaring",
        "projects": "Projecten",
        "uniProjects": "Universiteitsprojecten",
        "contact": "Contactformulier",
        "hero.swipe": "Scroll naar beneden voor meer",
        "project.source": "Bron",
        "project.preview": "Voorbeeld",
        "project.post": "Bijdrage",
        "project.in_development": "In ontwikkeling",
        "contact.foreword": "Bedankt voor je bezoek. Of je nu een recruiter bent met een interessante kans, een team vertegenwoordigt dat een developer zoekt, een idee hebt om samen te bouwen of gewoon wilt connecten: laat gerust hieronder een bericht achter. Ik sta altijd open voor contact en neem zo snel mogelijk contact met je op.",
        "contact.name": "Je volledige naam",
        "contact.email": "Je e-mailadres",
        "contact.type": "Type bericht",
        "contact.option": "-- selecteer een optie --",
        "contact.option.work": "Werk & Samenwerking",
        "contact.option.networking": "Netwerken & Professionele connecties",
        "contact.option.feedback": "Feedback / suggestie voor de website",
        "contact.option.job": "Vacatures & Recruiter outreach",
        "contact.option.other": "Overig",
        "contact.message": "Bericht",
        "contact.send": "Verzenden",
        "contact.sending": "Aan het verzenden...",
        "contact.success": "Succesvol verzonden",
        "contact.err_captcha": "Het lijkt erop dat je het reCAPTCHA-vakje bent vergeten. Vink dit aan om je bericht te verzenden.",
        "contact.err_select": "Jij hebt 'Type bericht' niet ingevuld in het vak. Selecteer dit a.u.b.",
        "contact.err_general": "Er is een fout opgetreden! Probeer het later opnieuw of mail rechtstreeks naar contact@badamczyk.eu",
        "contact.disclaimer1": "Berichten worden verzonden via ",
        "contact.disclaimer2": " en worden niet opgeslagen op de server",
    },
    fr: {
        "about": "À propos de moi",
        "experience": "Expérience",
        "projects": "Projets",
        "uniProjects": "Projets universitaires",
        "contact": "Formulaire de contact",
        "hero.swipe": "Glissez vers le bas pour découvrir la suite",
        "project.source": "Source",
        "project.preview": "Aperçu",
        "project.post": "Publication",
        "project.in_development": "En développement",
        "contact.foreword": "Merci pour votre visite. Que vous soyez recruteur avec une opportunité, une équipe à la recherche d'un développeur, que vous ayez une idée de projet à concrétiser ensemble ou simplement l'envie d'échanger, n'hésitez pas à me laisser un message ci-dessous. Je serai ravi de vous lire et vous répondrai dans les plus brefs délais.",
        "contact.name": "Votre nom complet",
        "contact.email": "Votre e-mail",
        "contact.type": "Type de message",
        "contact.option": "-- sélectionnez une option --",
        "contact.option.work": "Travail & Collaboration",
        "contact.option.networking": "Réseautage & Contacts professionnels",
        "contact.option.feedback": "Commentaires / suggestions pour ce site",
        "contact.option.job": "Offres d'emploi & Contact recruteur",
        "contact.option.other": "Autre",
        "contact.message": "Message",
        "contact.send": "Envoyer",
        "contact.sending": "Envoi en cours...",
        "contact.success": "Envoyé avec succès",
        "contact.err_captcha": "Il semblerait que vous ayez oublié la case reCAPTCHA. Veuillez la cocher pour envoyer votre message.",
        "contact.err_select": "Vous n'avez pas rempli le champ 'Type de message' dans l'encadré. Veuillez le sélectionner.",
        "contact.err_general": "Une erreur s'est produite ! Veuillez réessayer plus tard ou envoyer un e-mail directement à contact@badamczyk.eu",
        "contact.disclaimer1": "Les messages sont envoyés via ",
        "contact.disclaimer2": " et ne sont pas stockés sur le serveur",
    },
} as const;

export function useTranslations(lang: keyof typeof ui) {
    return function t(key: keyof typeof ui[typeof defaultLang]) {
        return ui[lang][key] || ui[defaultLang][key];
    }
}